name: ticket
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  intl: ^0.17.0
  modal_bottom_sheet: ^2.1.2
  paged_vertical_calendar: ^1.1.4
  scrollable_positioned_list: ^0.3.4
  shimmer: ^2.0.0
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
